-- ====================================================================
-- 🌀 2.5D Dimensional Shift - Supabase 雲端關卡庫初始化 SQL 腳本
-- 請前往 Supabase 儀表板 -> SQL Editor -> New Query，貼上並執行此腳本
-- ====================================================================

-- 1. 建立關卡資料表 (levels)
CREATE TABLE IF NOT EXISTS public.levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    creator TEXT DEFAULT '神秘旅人',
    world JSONB NOT NULL,
    obstacles JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 開啟 Row Level Security (RLS) 安全保護
ALTER TABLE public.levels ENABLE ROW LEVEL SECURITY;

-- 3. 建立安全政策 (Policies)
-- 允許所有人 (匿名用戶) 讀取關卡列表
CREATE POLICY "允許匿名使用者讀取關卡" 
ON public.levels 
FOR SELECT 
USING (true);

-- 允許所有人 (匿名用戶) 新增關卡
CREATE POLICY "允許匿名使用者上傳關卡" 
ON public.levels 
FOR INSERT 
WITH CHECK (true);

-- 4. 建立索引以加速按時間排序的查詢
CREATE INDEX IF NOT EXISTS idx_levels_created_at ON public.levels (created_at DESC);
