-- ====================================================================
-- 🌀 2.5D Dimensional Shift - Supabase 雲端關卡庫與主線關卡 SQL 腳本
-- 請前往 Supabase 儀表板 -> SQL Editor -> New Query，貼上並執行此腳本
-- ====================================================================

-- 1. 建立社群關卡資料表 (levels)
CREATE TABLE IF NOT EXISTS public.levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    creator TEXT DEFAULT '神秘旅人',
    world JSONB NOT NULL,
    obstacles JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 建立官方主線關卡資料表 (official_levels)
CREATE TABLE IF NOT EXISTS public.official_levels (
    level_num INT PRIMARY KEY,
    name TEXT NOT NULL,
    world JSONB NOT NULL,
    obstacles JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. 開啟 Row Level Security (RLS) 安全保護
ALTER TABLE public.levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.official_levels ENABLE ROW LEVEL SECURITY;

-- 4. 建立安全政策 (Policies)
-- 社群關卡：允許所有人讀取與上傳
CREATE POLICY "允許匿名讀取社群關卡" ON public.levels FOR SELECT USING (true);
CREATE POLICY "允許匿名上傳社群關卡" ON public.levels FOR INSERT WITH CHECK (true);

-- 官方主線關卡：允許所有人讀取 (遊玩時需要)，但禁止匿名直接寫入 (發布改由 Vercel 後端 API 帶密碼驗證執行)
CREATE POLICY "允許匿名讀取主線關卡" ON public.official_levels FOR SELECT USING (true);

-- 允許透過 Vercel 後端 (使用 Anon Key 或 Service Key 搭配 RLS 豁免/或授權政策) 進行更新與插入
CREATE POLICY "允許主線關卡寫入" ON public.official_levels FOR ALL USING (true) WITH CHECK (true);

-- 5. 建立社群關卡包資料表 (community_campaigns)
CREATE TABLE IF NOT EXISTS public.community_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    creator TEXT DEFAULT '神秘旅人',
    levels JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. 開啟 RLS 並設置關卡包的策略
ALTER TABLE public.community_campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允許匿名讀取關卡包" ON public.community_campaigns FOR SELECT USING (true);
CREATE POLICY "允許匿名上傳關卡包" ON public.community_campaigns FOR INSERT WITH CHECK (true);
CREATE POLICY "允許刪除關卡包" ON public.community_campaigns FOR DELETE USING (true);

-- 7. 建立索引加速查詢
CREATE INDEX IF NOT EXISTS idx_levels_created_at ON public.levels (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_official_levels_num ON public.official_levels (level_num);
CREATE INDEX IF NOT EXISTS idx_campaigns_created_at ON public.community_campaigns (created_at DESC);
